fos_user_security_login:
    path: /app/login
    defaults:
        _controller: FOSUserBundle:Security:login

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /app

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
